import { NextRequest, NextResponse } from "next/server";
import nodemailer from 'nodemailer';

export async function POST(request: NextRequest) {
  try {
    const { itineraryData, destinationName, userContactInfo } = await request.json();
    
    // Create a nodemailer transporter
    const transporter = nodemailer.createTransport({
      service: 'gmail', // You can change this to another service
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASSWORD, // Use app-specific password for better security
      },
    });

    // Format the schedule as plain text
    interface Activity {
        time?: string;
        description?: string;
        location?: string;
    }

    interface DaySchedule {
        title?: string;
        description?: string;
        activities: Activity[];
    }

    const formatScheduleText = (schedule: DaySchedule[] | null | undefined): string => {
        if (!schedule || !Array.isArray(schedule)) return 'No schedule information available';
        
        return schedule.map((day, index) => {
            let dayText = `DAY ${index + 1}: ${day.title || ''}\n`;
            dayText += `${day.description || ''}\n\n`;
            
            dayText += day.activities.map(activity => {
                let actText = `* ${activity.time || ''}: ${activity.description || ''}`;
                if (activity.location) {
                    actText += `\n  Location: ${activity.location}`;
                }
                return actText;
            }).join('\n\n');
            
            return dayText;
        }).join('\n\n' + '-'.repeat(40) + '\n\n');
    };

    // Format the budget as plain text
    const formatBudgetText = (budget: { totalCost: any; currency: any; breakdown: any; notes: any; }): string => {
      if (!budget) return 'No budget information available';
      
      let budgetText = `Total Estimated Cost: ${budget.totalCost || ''}\n`;
      budgetText += `Currency: ${budget.currency || ''}\n\n`;
      
      budgetText += 'BREAKDOWN:\n';
      if (budget.breakdown) {
        Object.entries(budget.breakdown).forEach(([category, amount]) => {
          budgetText += `* ${category}: ${amount}\n`;
        });
      }
      
      if (budget.notes) {
        budgetText += `\nNotes: ${budget.notes}`;
      }
      
      return budgetText;
    };

    // Format the packing list as plain text
    const formatPackingListText = (packingList: any[]): string => {
      if (!packingList || !Array.isArray(packingList)) return 'No packing list available';
      
      return packingList.map(item => `* ${item}`).join('\n');
    };

    // Format local tips as plain text
    const formatTipsText = (tips: any[]): string => {
      if (!tips || !Array.isArray(tips)) return 'No local tips available';
      
      return tips.map(tip => `* ${tip}`).join('\n');
    };

    // Format transport recommendations as plain text
    const formatTransportText = (transport: any[]): string => {
      if (!transport || !Array.isArray(transport)) return 'No transport recommendations available';
      
      return transport.map(item => `* ${item}`).join('\n');
    };
    
    // Create a comprehensive plain text email with the full itinerary
    const emailContent = `
TRAVEL ITINERARY FOR ${itineraryData.destination.toUpperCase()}
${'='.repeat(60)}

Dear ${userContactInfo?.name || 'Traveler'},

Here is your requested itinerary for ${itineraryData.destination}. 
We hope you find this information helpful for planning your trip.

${'='.repeat(60)}
TRIP SUMMARY
${'='.repeat(60)}
${itineraryData.summary || 'No summary available.'}

${'='.repeat(60)}
DAILY SCHEDULE
${'='.repeat(60)}

${formatScheduleText(itineraryData.schedule)}

${'='.repeat(60)}
BUDGET
${'='.repeat(60)}

${formatBudgetText(itineraryData.budget)}

${'='.repeat(60)}
PACKING LIST
${'='.repeat(60)}

${formatPackingListText(itineraryData.packingList)}

${'='.repeat(60)}
LOCAL TIPS
${'='.repeat(60)}

${formatTipsText(itineraryData.localTips)}

${'='.repeat(60)}
TRANSPORT RECOMMENDATIONS
${'='.repeat(60)}

${formatTransportText(itineraryData.transportRecommendations)}

${'='.repeat(60)}
This itinerary was generated by Travel App. 
Enjoy your trip to ${itineraryData.destination}!

Contact Information:
Name: ${userContactInfo?.name || 'N/A'}
Email: ${userContactInfo?.email || 'N/A'}
Phone: ${userContactInfo?.phone || 'N/A'}
`;
    
    // Create the JSON attachment
    const jsonContent = JSON.stringify(itineraryData, null, 2);
    const filename = `${destinationName.replace(/\s+/g, '_')}_itinerary.json`;
    
    // Prepare recipients list - include both hardcoded email and user email
    const recipients = ['dev@rbdesigntech.com']; // Default recipient
    if (userContactInfo?.email) {
      recipients.push(userContactInfo.email);
    }
    
    // Send the email with plain text content and JSON attachment
    const info = await transporter.sendMail({
      from: process.env.EMAIL_USER,
      to: recipients.join(', '), // Send to multiple recipients
      subject: `Travel Itinerary for ${destinationName}`,
      text: emailContent, // Using text instead of html
      attachments: [
        {
          filename: filename,
          content: jsonContent,
          contentType: 'application/json',
        },
      ],
    });
    
    return NextResponse.json({ success: true, messageId: info.messageId });
  } catch (error: any) {
    console.error('Error sending email:', error);
    return NextResponse.json(
      { success: false, error: error.message || 'Failed to send email' },
      { status: 500 }
    );
  }
}
